var firstname_count=1;var middlename_count=1;var lastname_count=1;var idnumber_count=1;var passportnumber_count=1;var mobile_count=1;var sponsor_count=1;var email_count=1;var username_count=1;var password_count=1;var confirmpassword_count=1;var reg_array=[];window.onload=function(){var field=document.getElementById("Sponsor").value;var msg="";var dir="/signcontroller/checkActiveUsernameExists/";if(field===""){msg="Compulsory field * ";}else if(/^[a-zA-Z0-9]*$/.test(field.trim())==false){msg="Invalid username";}else{var results=$.ajax({url:dir,method:"POST",async:false,data:{id:field},success:function(){}}).responseText;msg=results.trim();}
error_sponsor.innerHTML=msg;if(msg==='Sponsor id not found'){sponsor_count=1;sponsor_tick.innerHTML="<img src='/images/checkmark_2.png'/>";error_sponsor.innerHTML="Invalid username";var element=document.getElementById("Proceed");element.classList.add("btn-disable");}else if(msg==="<div class='l'>Sponsor is available</div>"){sponsor_count=0;reg_array['sponsor']=field.trim();sponsor_tick.innerHTML="<img src='/images/checkmark.png'/>";var dir="/signcontroller/checkActiveUsernameExists_2/";var results=$.ajax({url:dir,method:"POST",async:false,data:{id:field},success:function(){}}).responseText;msg=results.trim();if(msg!=="Your sponsor currently has no available spillover spots"){error_sponsor.innerHTML="<div class='l'>"+msg+"</div>";var element=document.getElementById("Proceed");element.classList.remove("btn-disable");}else{error_sponsor.innerHTML=msg;sponsor_count=1;sponsor_tick.innerHTML="<img src='/images/checkmark_2.png'/>";var element=document.getElementById("Proceed");element.classList.add("btn-disable");}}else{sponsor_count=1;sponsor_tick.innerHTML="<img src='/images/checkmark_2.png'/>";var element=document.getElementById("Proceed");element.classList.add("btn-disable");}}
$(function(){$('#Firstname').keyup(function(){var field=document.getElementById("Firstname").value;var msg="";if(field===""){msg="Compulsory field * ";}else if(/^[a-zA-Z]*$/.test(field.trim())==false){msg="Invalid name";}
error_name.innerHTML=msg;if(msg!=""){firstname_tick.innerHTML="<img src='/images/checkmark_2.png'/>";firstname_count=1;}else{firstname_tick.innerHTML="<img src='/images/checkmark.png'/>";firstname_count=0;reg_array['firstname']=field.trim().trim();}
error_name.innerHTML=msg;});});$(function(){$('#Firstname').click(function(){var field=document.getElementById("Firstname").value;var msg="";if(field===""){msg="Compulsory field * ";}else if(/^[a-zA-Z]*$/.test(field.trim())==false){msg="Invalid name";}
error_name.innerHTML=msg;if(msg!=""){firstname_tick.innerHTML="<img src='/images/checkmark_2.png'/>";firstname_count=1;}else{firstname_tick.innerHTML="<img src='/images/checkmark.png'/>";firstname_count=0;reg_array['firstname']=field.trim();}
error_name.innerHTML=msg;});});$(function(){$('#Middlename').keyup(function(){var field=document.getElementById("Middlename").value;var msg="";if(/^[a-zA-Z]*$/.test(field.trim())==false){msg="Incorrect info supplied";}
error_middlename.innerHTML=msg;if(msg!=""){middlename_count=1;middlename_tick.innerHTML="<img src='/images/checkmark_2.png'/>";}else{middlename_count=0;reg_array['middlename']=field.trim();middlename_tick.innerHTML="<img src='/images/checkmark.png'/>";}});});$(function(){$('#Middlename').click(function(){var field=document.getElementById("Middlename").value;var msg="";if(/^[a-zA-Z]*$/.test(field.trim())==false){msg="Incorrect info supplied";}
error_middlename.innerHTML=msg;if(msg!=""){middlename_count=1;middlename_tick.innerHTML="<img src='/images/checkmark_2.png'/>";}else{middlename_count=0;reg_array['middlename']=field.trim();middlename_tick.innerHTML="<img src='/images/checkmark.png'/>";}});});$(function(){$('#Lastname').keyup(function(){var field=document.getElementById("Lastname").value;var msg="";if(field===""){msg="Compulsory field * ";}else if(/^[a-zA-Z]*$/.test(field.trim())==false){msg="Invalid surname";}
error_lastname.innerHTML=msg;if(msg!=""){lastname_count=1;lastname_tick.innerHTML="<img class='tick' src='/images/checkmark_2.png'/>";}else{lastname_count=0;reg_array['lastname']=field.trim();lastname_tick.innerHTML="<img class='tick' src='/images/checkmark.png'/>";}});});$(function(){$('#Lastname').click(function(){var field=document.getElementById("Lastname").value;var msg="";if(field===""){msg="Compulsory field * ";}else if(/^[a-zA-Z]*$/.test(field.trim())==false){msg="Invalid surname";}
error_lastname.innerHTML=msg;if(msg!=""){lastname_count=1;lastname_tick.innerHTML="<img class='tick' src='/images/checkmark_2.png'/>";}else{lastname_count=0;reg_array['lastname']=field.trim();lastname_tick.innerHTML="<img class='tick' src='/images/checkmark.png'/>";}});});function populateCountryCode(){var field=document.getElementById("Country").value;var dir="/signcontroller/populate/";$.ajax({url:dir,method:"POST",data:{iso:field},success:function(data){$('#MobileNumber').val(data);}})
if(field=='ZA'){$('.idNumber').show();$('.passportNumber').hide();}
else{$('.idNumber').hide();$('.passportNumber').show();}}
$(function(){$('#PassportNumber').keyup(function(){var field=document.getElementById("PassportNumber").value;field=field.trim();field=field.replace(/\s/g,'');var msg="";var dir="/signcontroller/checkPassportExists/";if(field===""){msg="Compulsory field * ";}else if(/^[a-zA-Z0-9]*$/.test(field.trim())==false){msg="Invalid Passport number";}else{var results=$.ajax({url:dir,method:"POST",async:false,data:{id:field},success:function(){}}).responseText;msg=results.trim();}
$('#PassportNumber').val(field);error_passport.innerHTML=msg;if(msg!=""){passportnumber_count=1;passportnumber_tick.innerHTML="<img src='/images/checkmark_2.png'/>";}else{passportnumber_count=0;reg_array['passport']=field.trim();passportnumber_tick.innerHTML="<img src='/images/checkmark.png'/>";}});});$(function(){$('#PassportNumber').click(function(){var field=document.getElementById("PassportNumber").value;field=field.trim();field=field.replace(/\s/g,'');var msg="";var dir="/signcontroller/checkPassportExists/";if(field===""){msg="Compulsory field * ";}else if(/^[a-zA-Z0-9]*$/.test(field.trim())==false){msg="Invalid Passport number";}else{var results=$.ajax({url:dir,method:"POST",async:false,data:{id:field},success:function(){}}).responseText;msg=results.trim();}
$('#PassportNumber').val(field);error_passport.innerHTML=msg;if(msg!=""){passportnumber_count=1;passportnumber_tick.innerHTML="<img src='/images/checkmark_2.png'/>";}else{passportnumber_count=0;reg_array['passport']=field.trim();passportnumber_tick.innerHTML="<img src='/images/checkmark.png'/>";}});});$(function(){$('#IdNumber').keyup(function(){var field=document.getElementById("IdNumber").value;var gender=document.getElementById("Gender").value;field=field.trim();field=field.replace(/\s/g,'');var ver_gender=Number(field.substring(6,10));var msg="";var result;var dir="/signcontroller/checkIdExists/";if(field===""){msg="Your identity number is required";}else if(/^[0-9\-]*$/.test(field.trim())==false){msg="Invalid South African ID number";}else if(field.length!=13){msg="Invalid South African ID number";}else if((gender=='Male'&ver_gender<5000)||(gender=='Female'&ver_gender>4999)){msg="SA ID Number and Gender do not correspond";}else{var results=$.ajax({url:dir,method:"POST",async:false,global:false,dataType:"text",data:{id:field},success:function(){}}).responseText;result=results;if(result.trim()=="ID number already signed up")
msg=result;}
$('#IdNumber').val(field);if(msg===""){error_idnumber.innerHTML=msg;idnumber_count=0;reg_array['idnumber']=field.trim();idnumber_tick.innerHTML="<img src='/images/checkmark.png'/>";}else{error_idnumber.innerHTML=msg;idnumber_count=1;idnumber_tick.innerHTML="<img src='/images/checkmark_2.png'/>";}});$('#Gender').change(function(){var field=document.getElementById("IdNumber").value;var gender=document.getElementById("Gender").value;field=field.trim();field=field.replace(/\s/g,'');var ver_gender=Number(field.substring(6,10));var msg="";var result="";var dir="/signcontroller/checkIdExists/";if(field===""){msg=" ";}else if(/^[0-9\-]*$/.test(field.trim())==false){msg="Invalid South African ID number";}else if(field.length!=13){msg="Invalid South African ID number";}else if((gender=='Male'&ver_gender<5000)||(gender=='Female'&ver_gender>4999)){msg="SA ID Number and Gender do not correspond";}else{var results=$.ajax({url:dir,method:"POST",async:false,data:{id:field},success:function(){}}).responseText;result=results;if(result.trim()==="ID number already signed up")
msg=result;}
$('#IdNumber').val(field);if(msg===""){idnumber_count=0;reg_array['idnumber']=field.trim();error_idnumber.innerHTML=msg;idnumber_tick.innerHTML="<img src='/images/checkmark.png'/>";}else if(msg===" "){idnumber_count=0;reg_array['idnumber']=field.trim();error_idnumber.innerHTML=msg;idnumber_tick.innerHTML="";}else{idnumber_count=1;error_idnumber.innerHTML=msg;idnumber_tick.innerHTML="<img src='/images/checkmark_2.png'/>";}});});$(function(){$('#IdNumber').click(function(){var field=document.getElementById("IdNumber").value;var gender=document.getElementById("Gender").value;field=field.trim();field=field.replace(/\s/g,'');var ver_gender=Number(field.substring(6,10));var msg="";var result;var dir="/signcontroller/checkIdExists/";if(field===""){msg="Your identity number is required";}else if(/^[0-9\-]*$/.test(field.trim())==false){msg="Invalid South African ID number";}else if(field.length!=13){msg="Invalid South African ID number";}else if((gender=='Male'&ver_gender<5000)||(gender=='Female'&ver_gender>4999)){msg="SA ID Number and Gender do not correspond";}else{var results=$.ajax({url:dir,method:"POST",async:false,global:false,dataType:"text",data:{id:field},success:function(){}}).responseText;result=results;if(result.trim()=="ID number already signed up")
msg=result;}
$('#IdNumber').val(field);if(msg===""){error_idnumber.innerHTML=msg;idnumber_count=0;reg_array['idnumber']=field.trim();idnumber_tick.innerHTML="<img src='/images/checkmark.png'/>";}else{error_idnumber.innerHTML=msg;idnumber_count=1;idnumber_tick.innerHTML="<img src='/images/checkmark_2.png'/>";}});$('#Gender').change(function(){var field=document.getElementById("IdNumber").value;var gender=document.getElementById("Gender").value;field=field.trim();field=field.replace(/\s/g,'');var ver_gender=Number(field.substring(6,10));var msg="";var result="";var dir="/signcontroller/checkIdExists/";if(field===""){msg=" ";}else if(/^[0-9\-]*$/.test(field.trim())==false){msg="Invalid South African ID number";}else if(field.length!=13){msg="Invalid South African ID number";}else if((gender=='Male'&ver_gender<5000)||(gender=='Female'&ver_gender>4999)){msg="SA ID Number and Gender do not correspond";}else{var results=$.ajax({url:dir,method:"POST",async:false,data:{id:field},success:function(){}}).responseText;result=results;if(result.trim()==="ID number already signed up")
msg=result;}
$('#IdNumber').val(field);if(msg===""){idnumber_count=0;reg_array['idnumber']=field.trim();error_idnumber.innerHTML=msg;idnumber_tick.innerHTML="<img src='/images/checkmark.png'/>";}else if(msg===" "){idnumber_count=0;reg_array['idnumber']=field.trim();error_idnumber.innerHTML=msg;idnumber_tick.innerHTML="";}else{idnumber_count=1;error_idnumber.innerHTML=msg;idnumber_tick.innerHTML="<img src='/images/checkmark_2.png'/>";}});});$(function(){$('#MobileNumber').keyup(function(){var field=document.getElementById("MobileNumber").value;field=field.trim();field=field.replace(/\s/g,'');var msg="";if(field===""){msg="Compulsory field * ";}else if(/^[0-9 \-+]*$/.test(field.trim())==false){msg="Invalid cellphone number";}else if(field.length<10){msg="Invalid cellphone number";}
error_mobilenumber.innerHTML=msg;if(msg!=""){mobile_count=1;mobile_tick.innerHTML="<img src='/images/checkmark_2.png'/>";}else{mobile_count=0;reg_array['mobile']=field.trim();mobile_tick.innerHTML="<img src='/images/checkmark.png'/>";}});});$(function(){$('#MobileNumber').click(function(){var field=document.getElementById("MobileNumber").value;field=field.trim();field=field.replace(/\s/g,'');var msg="";if(field===""){msg="Compulsory field * ";}else if(/^[0-9 \-+]*$/.test(field.trim())==false){msg="Please enter a correct number";}else if(field.length<10){msg="Please enter a correct number";}
error_mobilenumber.innerHTML=msg;if(msg!=""){mobile_count=1;mobile_tick.innerHTML="<img src='/images/checkmark_2.png'/>";}else{mobile_count=0;reg_array['mobile']=field.trim();mobile_tick.innerHTML="<img src='/images/checkmark.png'/>";}});});$(function(){$('#Sponsor').keyup(function(){var field=document.getElementById("Sponsor").value;var msg="";var dir="/signcontroller/checkActiveUsernameExists/";if(field===""){msg="Compulsory field * ";}else if(/^[a-zA-Z0-9]*$/.test(field.trim())==false){msg="";}else{var results=$.ajax({url:dir,method:"POST",async:false,data:{id:field},success:function(){}}).responseText;msg=results.trim();}
error_sponsor.innerHTML=msg;if(msg==='Sponsor id not found'){sponsor_count=1;sponsor_tick.innerHTML="<img src='/images/checkmark_2.png'/>";error_sponsor.innerHTML='Invalid username';var element=document.getElementById("Proceed");element.classList.add("btn-disable");}else if(msg==="<div class='l'>Sponsor is available</div>"){sponsor_count=0;reg_array['sponsor']=field.trim();sponsor_tick.innerHTML="<img src='/images/checkmark.png'/>";var dir="/signcontroller/checkActiveUsernameExists_2/";var results=$.ajax({url:dir,method:"POST",async:false,data:{id:field},success:function(){}}).responseText;msg=results.trim();if(msg!=="Your sponsor currently has no available spillover spots"){error_sponsor.innerHTML="<div class='l'>"+msg+"</div>";var element=document.getElementById("Proceed");element.classList.remove("btn-disable");}else{error_sponsor.innerHTML=msg;sponsor_count=1;sponsor_tick.innerHTML="<img src='/images/checkmark_2.png'/>";var element=document.getElementById("Proceed");element.classList.add("btn-disable");}}else{sponsor_count=1;sponsor_tick.innerHTML="<img src='/images/checkmark_2.png'/>";var element=document.getElementById("Proceed");element.classList.add("btn-disable");}});});$(function(){$('#Sponsor').click(function(){var field=document.getElementById("Sponsor").value;var msg="";var dir="/signcontroller/checkActiveUsernameExists/";if(field===""){msg="Compulsory field * ";}else if(/^[a-zA-Z0-9]*$/.test(field.trim())==false){msg="";}else{var results=$.ajax({url:dir,method:"POST",async:false,data:{id:field},success:function(){}}).responseText;msg=results.trim();}
error_sponsor.innerHTML=msg;if(msg==='Sponsor id not found'){sponsor_count=1;sponsor_tick.innerHTML="<img src='/images/checkmark_2.png'/>";error_sponsor.innerHTML='Invalid username';var element=document.getElementById("Proceed");element.classList.add("btn-disable");}else if(msg==="<div class='l'>Sponsor is available</div>"){sponsor_count=0;reg_array['sponsor']=field.trim();sponsor_tick.innerHTML="<img src='/images/checkmark.png'/>";var dir="/signcontroller/checkActiveUsernameExists_2/";var results=$.ajax({url:dir,method:"POST",async:false,data:{id:field},success:function(){}}).responseText;msg=results.trim();if(msg!=="Your sponsor currently has no available spillover spots"){error_sponsor.innerHTML="<div class='l'>"+msg+"</div>";var element=document.getElementById("Proceed");element.classList.remove("btn-disable");}else{error_sponsor.innerHTML=msg;sponsor_count=1;sponsor_tick.innerHTML="<img src='/images/checkmark_2.png'/>";var element=document.getElementById("Proceed");element.classList.add("btn-disable");}}else{sponsor_count=1;sponsor_tick.innerHTML="<img src='/images/checkmark_2.png'/>";var element=document.getElementById("Proceed");element.classList.add("btn-disable");}});});$(function(){$('#EmailAddress').keyup(function(){var field=document.getElementById("EmailAddress").value;field=field.trim();field=field.replace(/\s/g,'');var msg="";var dir="/signcontroller/checkEmailExists/";if(field==""){msg="Compulsory field * ";}else if(/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{1,3})+$/.test(field.trim())==false){msg="Wrong email address format";}
error_email.innerHTML=msg;if(msg!=""){email_count=1;email_tick.innerHTML="<img src='/images/checkmark_2.png'/>";}else{email_count=0;reg_array['email']=field.trim();email_tick.innerHTML="<img src='/images/checkmark.png'/>";}});});$(function(){$('#EmailAddress').click(function(){var field=document.getElementById("EmailAddress").value;field=field.trim();field=field.replace(/\s/g,'');var msg="";var dir="/signcontroller/checkEmailExists/";if(field==""){msg="Compulsory field *";}else if(/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{1,3})+$/.test(field.trim())==false){msg="Hmmm, that’s not a valid email address.";}
error_email.innerHTML=msg;if(msg!=""){email_count=1;email_tick.innerHTML="<img src='/images/checkmark_2.png'/>";}else{email_count=0;reg_array['email']=field.trim();email_tick.innerHTML="<img src='/images/checkmark.png'/>";}});});$(function(){$('#Username').keyup(function(){var field=document.getElementById("Username").value;var msg="";var dir="/signcontroller/checkUsernameExists/";if(field===""){msg="Compulsory field * ";}else if(/^[a-zA-Z0-9]*$/.test(field.trim())==false){msg="Invalid username.";}else if(field.length<5){msg="Username need at least 5 characters";}else{var results=$.ajax({url:dir,method:"POST",async:false,data:{id:field},success:function(){}}).responseText;msg=results.trim();}
error_username.innerHTML=msg;if(msg==='Sorry this username is not available'){username_count=1;username_tick.innerHTML="<img src='/images/checkmark_2.png'/>";error_username.innerHTML='Username unavailable, try another one';}else if(msg==="<div class='l'>This username is available</div>"){username_count=0;reg_array['username']=field.trim();username_tick.innerHTML="<img src='/images/checkmark.png'/>";error_username.innerHTML='';}else{username_count=1;username_tick.innerHTML="<img src='/images/checkmark_2.png'/>";}});});$(function(){$('#Username').click(function(){var field=document.getElementById("Username").value;var msg="";var dir="/signcontroller/checkUsernameExists/";if(field===""){msg="Compulsory field * ";}else if(/^[a-zA-Z0-9]*$/.test(field.trim())==false){msg="Invalid username";}else if(field.length<5){msg="Username needs at least 5 characters";}else{var results=$.ajax({url:dir,method:"POST",async:false,data:{id:field},success:function(){}}).responseText;msg=results.trim();}
error_username.innerHTML=msg;if(msg==='Sorry this username is not available'){username_count=1;username_tick.innerHTML="<img src='/images/checkmark_2.png'/>";error_username.innerHTML='Username unavailable, try another one';}else if(msg==="<div class='l'>This username is available</div>"){username_count=0;reg_array['username']=field.trim();username_tick.innerHTML="<img src='/images/checkmark.png'/>";error_username.innerHTML='';}else{username_count=1;username_tick.innerHTML="<img src='/images/checkmark_2.png'/>";}});});$(function(){$('#Password').keyup(function(){var field=document.getElementById("Password").value;var msg="";field=field.trim();if(field===""){msg="Compulsory field * ";}else if(field.length<4){msg="Password is too short";}
if(msg===""){password_count=0;reg_array['password']=field.trim();password_tick.innerHTML="<img src='/images/checkmark.png'/>";error_password_2.innerHTML=msg;}else{password_count=1;password_tick.innerHTML="<img src='/images/checkmark_2.png'/>";error_password_2.innerHTML=msg;}});});$(function(){$('#Password').click(function(){var field=document.getElementById("Password").value;var msg="";field=field.trim();if(field===""){msg="Compulsory field * ";}else if(field.length<4){msg="Password is too short";}
if(msg===""){password_count=0;reg_array['password']=field.trim();password_tick.innerHTML="<img src='/images/checkmark.png'/>";error_password_2.innerHTML=msg;}else{password_count=1;password_tick.innerHTML="<img src='/images/checkmark_2.png'/>";error_password_2.innerHTML=msg;}});});$(function(){$('#ConfirmPassword').keyup(function(){var field=document.getElementById("ConfirmPassword").value;var pass=document.getElementById("Password").value;var msg="";if(field!=pass){msg="Passwords are not the same";}
error_confirmpassword.innerHTML=msg;if(msg!=""){confirmpassword_tick.innerHTML="<img src='/images/checkmark_2.png'/>";confirmpassword_count=1;}else{confirmpassword_count=0;reg_array['password']=field.trim();confirmpassword_tick.innerHTML="<img src='/images/checkmark.png'/>";}});});$(function(){$('#ConfirmPassword').click(function(){var field=document.getElementById("ConfirmPassword").value;var pass=document.getElementById("Password").value;var msg="";if(field!=pass){msg="Passwords are not the same";}
error_confirmpassword.innerHTML=msg;if(msg!=""){confirmpassword_tick.innerHTML="<img src='/images/checkmark_2.png'/>";}else{confirmpassword_count=0;reg_array['password']=field.trim();confirmpassword_tick.innerHTML="<img src='/images/checkmark.png'/>";}});});$(function(){$('#AccHolder').keyup(function(){var field=document.getElementById("AccHolder").value;var msg="";if(field===""){msg="Compulsory field * ";}
error_accholder.innerHTML=msg;if(msg!=""){accholder_tick.innerHTML="<img src='/images/checkmark_2.png'/>";accholder_count=1;}else{accholder_tick.innerHTML="<img src='/images/checkmark.png'/>";accholder_count=0;reg_array['accholder']=field.trim();}
error_accholder.innerHTML=msg;});});$(function(){$('#AccHolder').click(function(){var field=document.getElementById("AccHolder").value;var msg="";if(field===""){msg="Compulsory field * ";}
error_accholder.innerHTML=msg;if(msg!=""){accholder_tick.innerHTML="<img src='/images/checkmark_2.png'/>";accholder_count=1;}else{accholder_tick.innerHTML="<img src='/images/checkmark.png'/>";accholder_count=0;reg_array['accholder']=field.trim();}
error_accholder.innerHTML=msg;});});$(function(){$('#Bank').keyup(function(){var field=document.getElementById("Bank").value;var msg="";if(field===""){msg="Compulsory field * ";}
error_bank.innerHTML=msg;if(msg!=""){bank_tick.innerHTML="<img src='/images/checkmark_2.png'/>";bank_count=1;}else{bank_tick.innerHTML="<img src='/images/checkmark.png'/>";bank_count=0;reg_array['bank']=field.trim();}
error_bank.innerHTML=msg;});});$(function(){$('#Bank').click(function(){var field=document.getElementById("Bank").value;var msg="";if(field===""){msg="Compulsory field * ";}
error_bank.innerHTML=msg;if(msg!=""){bank_tick.innerHTML="<img src='/images/checkmark_2.png'/>";bank_count=1;}else{bank_tick.innerHTML="<img src='/images/checkmark.png'/>";bank_count=0;reg_array['bank']=field.trim();}
error_bank.innerHTML=msg;});});$(function(){$('#AccNumber').keyup(function(){var field=document.getElementById("AccNumber").value;field=field.trim();field=field.replace(/\s/g,'');var msg="";if(field===""){msg="Compulsory field * ";}else if(/^[0-9 \-+]*$/.test(field.trim())==false){msg="Invalid account number";}else if(field.length<1){msg="Seems short";}
error_accnumber.innerHTML=msg;if(msg!=""){accnumber_count=1;accnumber_tick.innerHTML="<img src='/images/checkmark_2.png'/>";}else{accnumber_count=0;reg_array['accnumber']=field.trim();accnumber_tick.innerHTML="<img src='/images/checkmark.png'/>";}});});$(function(){$('#AccNumber').click(function(){var field=document.getElementById("AccNumber").value;field=field.trim();field=field.replace(/\s/g,'');var msg="";if(field===""){msg="Compulsory field * ";}else if(/^[0-9 \-+]*$/.test(field.trim())==false){msg="Account number must be numeric";}else if(field.length<1){msg="Seems short";}
error_accnumber.innerHTML=msg;if(msg!=""){accnumber_count=1;accnumber_tick.innerHTML="<img src='/images/checkmark_2.png'/>";}else{accnumber_count=0;reg_array['accnumber']=field.trim();accnumber_tick.innerHTML="<img src='/images/checkmark.png'/>";}});});$(function(){$('#Register').click(function(){$("#Firstname").keyup();$("#Lastname").keyup();$("#EmailAddress").keyup();$("#Username").keyup();$("#Password").keyup();$("#ConfirmPassword").keyup();$("#MobileNumber").keyup();$("#AccHolder").keyup();$("#AccNumber").keyup();$("#Bank").keyup();var bcode=document.getElementById("branchCode").value;var sponsor=document.getElementById("sponsor").value;reg_array['sponsor']=sponsor;bcode=bcode.trim();bcode=bcode.replace(/\s/g,'');var mycountry=document.getElementById("Country").value;var counter=firstname_count
+lastname_count
+mobile_count
+email_count
+username_count
+password_count
+confirmpassword_count
+accholder_count
+bank_count
+accnumber_count;if(counter==0){var dir="/signcontroller/signUp/";reg_array['branchcode']=bcode;var results=$.ajax({url:dir,method:"POST",async:false,data:{firstname:reg_array['firstname'],lastname:reg_array['lastname'],email:reg_array['email'],mobile:reg_array['mobile'],sponsor:reg_array['sponsor'],username:reg_array['username'],country:mycountry,password:reg_array['password'],accholder:reg_array['accholder'],bank:reg_array['bank'],branchcode:reg_array['branchcode'],accnumber:reg_array['accnumber']},success:function(){}}).responseText;msg=results.trim();$(window).scrollTop(0);if(msg!=='Congratulations member. You have been successfully registered'){element.classList.remove("alert-success");element.classList.add("alert-danger");error_message.innerHTML=msg;}else{window.location.href="/signcontroller/in/";}}else{element=document.getElementById("error_message");element.classList.add("alert");element.classList.remove("alert-success");element.classList.add("alert-danger");error_message.innerHTML='Ouch, please check your form data and submit again';$(window).scrollTop(0);return false;}});});$(function(){$('#Login').click(function(){var username=document.getElementById("Lusername").value;var password=document.getElementById("Lpassword").value;var dir="/signcontroller/login/";var results=$.ajax({url:dir,method:"POST",async:false,data:{uname:username,pword:password},success:function(){}}).responseText;msg=results.trim();if(msg=='unsuccessful'){element=document.getElementById("error_message");element.classList.add("alert");element.classList.add("alert-danger");error_message.innerHTML='Login Details Incorrect. Please try again.';$("html, body").animate({scrollTop:0},"slow");return false;}else if(msg=='blocked'){element=document.getElementById("error_message");element.classList.add("alert");element.classList.add("alert-danger");error_message.innerHTML='Your account has been blocked because you did not pay your upgrade';$("html, body").animate({scrollTop:0},"slow");return false;}else{window.location.href="/mydash/index/";}});});$(function(){$('#ShowPassword').click(function(){var x=document.getElementById("Password");if(x.type==="password"){x.type="text";}else{x.type="password";}
var x=document.getElementById("ConfirmPassword");if(x.type==="password"){x.type="text";}else{x.type="password";}});});$(function(){$('#UpdateAccountDetails').click(function(){$("#Firstname").keyup();$("#Lastname").keyup();$("#MobileNumber").keyup();var counter=firstname_count
+lastname_count
+mobile_count;if(counter==0){var dir="/mydash/updateMemberDetails/";var results=$.ajax({url:dir,method:"POST",async:false,data:{firstname:reg_array['firstname'],lastname:reg_array['lastname'],mobile:reg_array['mobile']},success:function(){}}).responseText;msg=results.trim();element=document.getElementById("error_message");element.classList.add("alert");element.classList.remove("alert-danger");element.classList.add("alert-success");error_message.innerHTML=msg;$("html, body").animate({scrollTop:0},"slow");return false;}else{element=document.getElementById("error_message");element.classList.add("alert");element.classList.remove("alert-success");element.classList.add("alert-danger");error_message.innerHTML='Fix errors below';$("html, body").animate({scrollTop:0},"slow");return false;}});});$(function(){$('#updateMemberPassword').click(function(){$("#Password").keyup();$("#ConfirmPassword").keyup();var counter=password_count
+confirmpassword_count;if(counter==0){var dir="/mydash/updateMemberPassword/";var results=$.ajax({url:dir,method:"POST",async:false,data:{password:reg_array['password']},success:function(){}}).responseText;msg=results.trim();element=document.getElementById("error_message_1");element.classList.add("alert");element.classList.remove("alert-danger");element.classList.add("alert-success");error_message_1.innerHTML=msg;}else{element=document.getElementById("error_message_1");element.classList.add("alert");element.classList.remove("alert-success");element.classList.add("alert-danger");error_message_1.innerHTML='Oh snap! Check your password please';}});});$(function(){$('#UpdateBankingDetails').click(function(){$("#AccHolder").keyup();$("#AccNumber").keyup();$("#Bank").keyup();var counter=accholder_count
+bank_count
+accnumber_count;if(counter==0){var dir="/mydash/updateBankingDetails/";var bcode=document.getElementById("branchCode").value;bcode=bcode.trim();bcode=bcode.replace(/\s/g,'');reg_array['branchcode']=bcode;var results=$.ajax({url:dir,method:"POST",async:false,data:{accholder:reg_array['accholder'],bank:reg_array['bank'],accnumber:reg_array['accnumber'],branchcode:reg_array['branchcode']},success:function(){}}).responseText;msg=results.trim();element=document.getElementById("error_message_2");element.classList.add("alert");element.classList.remove("alert-danger");element.classList.add("alert-success");error_message_2.innerHTML=msg;}else{element=document.getElementById("error_message_2");element.classList.add("alert");element.classList.remove("alert-success");element.classList.add("alert-danger");error_message_2.innerHTML='Fix banking errors below';}});});$(function(){$('#SendPassword').click(function(){var username=document.getElementById("Fusername").value;if(username===""){msg="Please type in your username";}
if(username!==""){var dir="/signcontroller/sendPassword/";var results=$.ajax({url:dir,method:"POST",async:false,data:{uname:username},success:function(){}}).responseText;msg=results.trim();if(msg=='unsuccessful'){element=document.getElementById("error_message");element.classList.add("alert");element.classList.remove("alert-success");element.classList.add("alert-danger");error_message.innerHTML='Error sending an email, please check your username';$("html, body").animate({scrollTop:0},"slow");return false;}else{element=document.getElementById("error_message");element.classList.add("alert");element.classList.remove("alert-danger");element.classList.add("alert-success");error_message.innerHTML='Access credentials SMS processed.';$("html, body").animate({scrollTop:0},"slow");return false;}}else{element=document.getElementById("error_message");element.classList.add("alert");element.classList.remove("alert-success");element.classList.add("alert-danger");error_message.innerHTML=msg;}});});